### ISSUE TITLE
Global workflow enabled to work with CCPP

### ISSUE THREAD

**Issue by arunchawla-NOAA** [ufs-community/ufs-s2s-model#36] opened 2020-03-05 19:07 UTC
Global workflow has a branch for the coupled system. Need to make sure that it works with CCPP. These issues need to be opened on the workflow repository and should be cited here for reference and status updates

**Comment by lgannoaa** [comment] 2020-03-05 19:35
Communicated with team and found out that we are using feature/coupled-crow branch of the global-workflow. Will start checkout and work on it.

**Comment by JessicaMeixner-NOAA** [comment] 2020-03-05 20:05
@lgannoaa if you go to https://github.com/NOAA-EMC/global-workflow/tree/feature/coupled-crow 
it will pull up the README with instructions to clone and run.  There should be no access issues, however the feature/coupled-crow branch is protected and you will have to push things via PRs back to this branch. 

@binli2337  can point you to the ocean post scripts/exes that are not yet in repositories (and what the best repository for them might be) if he has not already done that.

**Comment by jkuang-exploro** [comment] 2020-03-07 13:54
@lgannoaa The version that you've sent to me Friday will need to merge with the scripts in feature/coupled-crow branch. I will do it as my next task.

@JessicaMeixner-NOAA I will create another PR upgrading the scripts, taking in the CCPP/IPD changes while keeps current feature/coupled-crow reproducible with benchmark 3.1

**Comment by jkuang-exploro** [comment] 2020-03-09 21:32
@JessicaMeixner-NOAA and @lgannoaa I created PR #31 to address this. Trying to merge the newest version of the script into NOAA-EMC/feature/coupled-crow

**Comment by lgannoaa** [comment] 2020-03-12 15:29
Run and confirmed the a version of modularized exglobal fcst script solution can reproduce fcst in GFS low res on Hera. Some bug fix code sent to code manager @JianKuang-NOAA for merge to main repository.

**Comment by junwang-noaa** [comment] 2020-06-09 18:57
@JessicaMeixner-NOAA @JianKuang-NOAA May I ask what is the status of  this issue?

**Comment by JessicaMeixner-NOAA** [comment] 2020-06-09 19:07
Almost done.   This appears to be a duplicate of this issue: https://github.com/NOAA-EMC/global-workflow/issues/6

**Comment by JessicaMeixner-NOAA** [comment] 2020-10-02 13:12
I think this can be closed.  Do you agree @lgannoaa @JianKuang-NOAA

**Comment by lgannoaa** [comment] 2020-10-02 13:31
Yes. Please close it.

**Closed as completed** 2020-10-02 13:32 UTC
