### ISSUE TITLE
add CA regression test 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-s2s-model#83] opened 2020-05-05 20:16 UTC
Add a regression test (after the transition to rt.sh is finished) for CA. 

This will just be an extra regression test.  It can use NEMS or CMEPS mediator. 

@lisa-bengtsson  (I couldn't add you as a co-assignee, so I'm tagging you here).

**Comment by junwang-noaa** [comment] 2020-07-30 14:06
@lisa-bengtsson just let you know that the fv3 in s2s was updated, it contains the CA updates you put in. You can create CA test with the latest s2s repo now.

**Comment by lisa-bengtsson** [comment] 2020-07-30 14:10
@junwang-noaa thank you, @JessicaMeixner-NOAA let me know how I can help with this. There is a CA regression test for the ufs_weather_model that we can use as a starting point (e.g namelists etc).

**Comment by DeniseWorthen** [comment] 2020-10-02 10:17
I could add this test as a new s2s (c96/1deg) as part of PR [#194](https://github.com/ufs-community/ufs-s2s-model/pull/194) If you point me to the test that ufs-weather uses for CA I will start there.

**Comment by junwang-noaa** [comment] 2020-10-02 12:15
Thanks Denise, Please see
https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/tests/fv3_ca.
I think Lisa can help if you run into any issues.

**Comment by lisa-bengtsson** [comment] 2020-10-02 13:48
Thanks Denise!
Let me know if you need something. Jessica Meixner at EMC has some
experience running the CA in a coupled prototype 4 setup and can probably
also provide some guidance if necessary.

Lisa


---------------------------------
---------------------------------
Dr. Lisa Bengtsson
Phone : 1 (303) 497 5971
Research Scientist - Meteorologist
University of Colorado/NOAA Earth
System Research Lab
Email: lisa.bengtsson@noaa.gov
325 Broadway
Office: Skaggs Research Cntr 1D-702
Boulder, CO, USA 80303-3328

**Comment by junwang-noaa** [comment] 2020-10-22 19:29
CA test was committed to ufs-s2s in PR#194. The issue is closed.

**Closed as completed by junwang-noaa** 2020-10-22 19:29 UTC
