### ISSUE TITLE
Restart reproducibility

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-s2s-model#33] opened 2020-03-04 19:08 UTC
UFS-S2S must be able to reproduce on restart. The focus should be on achieving this for the CMEPS mediator.

**Comment by JessicaMeixner-NOAA** [comment] 2020-05-13 12:30
In respect to WW3 being included in the restart reproducibility: 
* WW3 is currently reproducible in standalone mode 
* ATM-> WW3 one way coupled using a leap-frog coupling scheme is reproducible 
For two-way coupling of ATM and WAV or for the full ufs-s2s-model with waves to be reproducible, WW3 will have to use the mediator instead of connectors to have the possibility of being reproducible (even if just one-way coupled to waves using the blocked coupling scheme).  

Once WW3 is connected to through the mediator there might be additional issues that will need to be addressed internally in WW3 since this cannot be tested until WW3 goes through connectors.

**Closed as completed** 2020-05-28 15:28 UTC
